name: Scheduled Task


on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  task:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run my CFML Task
      uses: docker://foundeo/minibox:latest
      with:
        entrypoint: /opt/box/box
        args: task run

